### ISSUE TITLE
order of drawing/dealing cards

### ISSUE THREAD

**Issue by blu-world** [rbtying/shengji#122]
Hi, the question I have is how is the cards are dealt/drawn with "auto draw" enabled? Is it always start from player1 or the landlord (庄家) ?  
The other thing would be useful/helpful is a shuffle button to further make players feels the cards are really shuffled.

**Comment by rbtying** [comment]
A few answers to your questions!

1. "auto-draw" just clicks the draw button for you after 250 milliseconds have passed since the button was activated
2. the draw order is fixed (left to right in the player order, wrapped). the first person to draw is randomly selected if there is no landlord. If there is a landlord, the landlord is the first person to draw.
3. this is interesting! the card deck is shuffled uniformly once the "start game" button is clicked. Unfortunately, it turns out that a uniform distribution isn't what players *really* expect: when playing the game in the real world, people rarely permute the cards enough to approach a uniformly random shuffle. While we could definitely add a shuffle button, it is mathematically equivalent to a button that does nothing right now...

**Comment by blu-world** [comment]
Thx for the quick response and the explanation of the drawing order.
The 3rd one is more of psychological then the logical. But still the deck.shuffle() does change the order of the cards though.
Thx for the info!
