### ISSUE TITLE
Configurable advancement threshold(s); also, separate level from trump rank

### ISSUE THREAD

**Issue by Claire-Zheng** [rbtying/shengji#141]
We'd like to have an option in the game setting that could select the default amount of points for a level-up. 

For a 4 decks card game, the current logic is the opposing team must get 160 points to win, 240 to go up 1 level, 320 to go up 2 levels, etc. 

The logic we play is attributing 10 for 1 level. If the opposing team only gets 110 points, each defending team member goes up 5 levels. If the opposing team gets 230 points, each opposing member goes up 7 levels. 

For example, if in several games, the levels they've accumulated from the past rounds are: 
A-24,  B-8,  C-12,  D-24,  E-17,  F-36,  G-19, 
the trump rankings for them are:
A-11,  B-8,  C-12,  D-11,  E-4,   F-10,   G-6. 

Additionally, if the opposing team gets 0, there will be an awarding level added for defending team, so instead of going up 16 levels, all defenders go up 17 levels. 

With this format, every 5/10/K card is important, and every trick must be played carefully. My parents have played this format for nearly 10 years, and it has made it much for fun for them, so they'd appreciate it immensely if it could get implemented!

**Comment by rbtying** [comment]
Interesting! I've never heard of people playing this way :)

So, basically, the idea here is that the midpoint is the same (40% of points for turnover), but the offsets from the midpoint are in 10s rather than (number of decks * 20)?

Implementing the offsets is easy enough, but we'd also have to implement wraparound for levels -- right now, the level and trump number are directly linked, which is a non-issue because it takes a really long time to get to the end of the game. We would also have to add a UI for specifying which wraparound we're on for the level, since a dropdown with 100 items for rank is probably not a good UX.

**Comment by Claire-Zheng** [comment]
Yes - that's the idea!

Could you clarify your last paragraph by chance? 

For some clarification on my part (if I've understood the situation with the level wraparounds):
- a person's trump rank should be their level % 13, no one gets to choose what trump rank they get to play
- their level is the accumulation of the levels they've accumulated from the past games
- so each person has a level and their trump rank (which is just level % 13), and when beginning the game, they must flip their own trump rank

**Comment by rbtying** [comment]
Since the game doesn't store any state across restarts, and to allow people to continue games that they started offline or in other contexts, there's an option in the UI to set your current level and the current landlord. That UI is currently just a dropdown for valid levels, which is nice and easy because there aren't that many.

The game automatically tracks your level across rounds, but this is only in the context of a single play session.

**Comment by Claire-Zheng** [comment]
I see - I meant to say that the level should equal the accumulation of all the rounds played in the current session, and there is no tracking of level state across a restart (e.g. when you restart the game on another day, all players will start at trump rank 2, or whatever that's provided for them to choose from, so the UI for rank selection in the continuation option doesn't have to change).
