### ISSUE TITLE
Ordering of required plays in 4 or more decks are questionable.

### ISSUE THREAD

**Issue by chnlyi** [rbtying/shengji#205]
When someone plays AAAA, if you don't have a triplet, you just have to submit any 2 pairs. It should be tractors of pairs if you have any, right?
There is another one. When someone plays AAAKKK, the current ordering of required plays is something like 3322XX (if you have 3322555). Shouldn't it be 55522X?

**Comment by rbtying** [comment]
thanks for reporting! I think this is an area where everyone plays with slightly different rules, so it's possible my understanding isn't the same as yours.

1. When I play, n-tuples never force tractors -- if you have enough pairs (n/2 pairs) to avoid playing your tractor, you don't have to play your tractor. This comes up pretty rarely in practice, though.

2. I think there is ambiguity here, i.e. whether AAAKKK decomposes first to (AAA)(KKK) or (AAKK)(AK). So you end up with the following decompositions:

AAAKKK => (AAA)(KKK) => (AAA)(KK)(X) => (AA)(KK)(X)(X) => (AA)(X)(X)(X)(X)=> (X)(X)(X)(X)(X)(X)

and

AAAKKK => (AAKK)(X)(X) => (AA)(KK)(X)(X) => (AA)(X)(X)(X)(X) => (X)(X)(X)(X)(X)(X)

Arguably, you could imagine some combined decomposition which inserts (AAKK)(X)(X) after (AAA)(KK)(X) and before (AA)(KK)(X)(X) -- but I'm not sure what the general implementation of that rule would be. Maybe we can do some dynamic programming on group length?

I don't remember which one the game implements -- I think I just picked one -- but if you have a more examples, we can see if we can derive self-consistent rules for them? In general, the game prefers to be *less* restrictive over *more* restrictive, since you can take back plays and handle odd cases informally.

**Comment by chnlyi** [comment]
Thanks a lot for replying so quickly and in such detail.
These are of course subject to personal preference. Is it possible to
introduce rule settings for different preferences for ordering?
For the # 1 situation, don't you think 4 or more-tuples are rarer than
tractors and therefore should be rewarded to be able to beat more advanced
cards, like tractors if you don't have triplets?
For the # 2 situation, the correct order is like this: AAAKKK => (AAA)(KKK)
=> (AAA)(KK)(X) =>  (AAKK)(X)(X) => (AA)(KK)(X)(X) => (AA)(X)(X)(X)(X)=>
(X)(X)(X)(X)(X)(X)

**Comment by rbtying** [comment]
In general, I'm open to people contributing rule sets that they play with, as long as they are behind a game setting! I tend to implement the ones that I understand better (i.e. the ones I have played with).

1. most people I know don't believe that a 3-tuple should require 3/4s of a tractor to be played. However, the prior probability of a triple is lower than the prior probability of a tractor [0]. so, I'm not sure the probability argument would lead to the idea that a 4-tuple should draw a tractor if a 3-tuple should not. since this isn't particularly consistent, it's hard to write a generalizable rule... especially if there's a longer tractor (i.e. 3x2 tractor vs 3-of-a-kind is obvious; 2x3 tractor vs 3-of-a-kind is less so)

2. I believe the current implementation simultaneously decomposes (AAAKKK) => (AAA)(KKK) and (AAAKKK) => (AAKK)(X)(X), and then the former decomposes to (AAA)(KK)(X). this is because the format (AAA)(KK)(X) doesn't require a tractor, and non-rectangular tractors aren't valid plays. We should come up with some test cases (PRs accepted!) for making sure the end result is correct, though.


[0]
```
Stats for 4 players, 4 decks
1-tuple observed: 22.98375
2-tuple observed: 11.44625
3-tuple observed: 2.44625
4-tuple observed: 0.19625
2x2-tractor observed: 3.54375
3x2-tractor observed: 0.65725
4x2-tractor observed: 0.04925

Stats for 5 players, 4 decks
1-tuple observed: 22.2642
2-tuple observed: 8.2652
3-tuple observed: 1.2954
4-tuple observed: 0.07980000000000001
2x2-tractor observed: 2.0524
3x2-tractor observed: 0.2874
4x2-tractor observed: 0.014599999999999998

Stats for 6 players, 4 decks
1-tuple observed: 21.1065
2-tuple observed: 6.2124999999999995
3-tuple observed: 0.7781666666666666
4-tuple observed: 0.0335
2x2-tractor observed: 1.2874999999999999
3x2-tractor observed: 0.141
4x2-tractor observed: 0.005666666666666667

```

**Comment by xiaofan-iit** [comment]
I would like to suggest we change the ordering such that a four-of-a-kind (rare) beats a regular tractor. For example, with 4 or more decks, trump 2 spade, 3333 (heart) should beat AAKK (heart). I understand that there are different preferences of rules. Can we add an option in the game settings such that four-of-a-kind is treated superior than a regular tractor?

**Comment by rbtying** [comment]
@xiaofan-iit thanks for pinging on this issue!

This will require some restructuring of how trick-format decomposition works, which is also necessary for other issues. I haven't yet spent much time reasoning about how to do so in a generally meaningful way. For example, while four decks has some edge cases that we can adjust the ordering for, it's less clear to me if there's a generalization that holds for N decks

the primary question is, if KKKK requires you to play 2233, does it require you to play 2233 before or after 444X? If before, then this is inconsistent with 2233 preferring 4466 over 444X. If after, then does 444 require that you play 223 and break a 2233 tractor (over playing 557, non-tractor?)

**Comment by chnlyi** [comment]
Hi, Robert, I am glad you are still working on this.
To answer your primary question, I will give you the following example:
KKKKK requires AAAA2. Then AAAA22. Then AAA23. Then KKQQ2. Then KK772. Then KK234. Then KQ234. 
I know it's a little complicated but it is very intuitive.

**Comment by rbtying** [comment]
> KKKKK requires AAAA2. Then AAAA22. Then AAA23. Then KKQQ2. Then KK772. Then KK234. Then KQ234.

Presumably KKKKKK requires (at some point) QQQJJJ. So the decomposition for KKKKK ought to require at some point QQQJJ in order to have a total ordering, right?

**Comment by chnlyi** [comment]
I think QQQJJ will be no difference with QQQXX, where XX is any pair. But
if it's easier for you to implement it in that way, I think that's OK

**Comment by rbtying** [comment]
I guess the bigger question, then, is whether there is a single total ordering of play-requirements, or if every initial play needs to be separately enumerated. Will think about this a bit more!

**Comment by xiaofan-iit** [comment]
Thanks for the discussion. Here is what we have ordered: for 4 decks of cards: 3333 requires a triplet first such as AAAx; if no triplet, then a tractor such as AAKK; if no triplet or tractor, then two pairs. We have not thought about the situation of 5 or more decks of cards. It is more complicated and not easy to generalize. Let me try 5 decks of cards: 33333 requires four-of-a-kind first such as AAAAx, then a triplet with adjacent pairs such as AAAKK, then a triplet and a pair such as AAAJJ, then a triplet plus two singles such as AAAJQ, then a regular tractor plus a single such as AAKKx, then two pairs plus a single. Usually, we do not see six-of-a-kind such as 333333 occurs in practice and can leave those rare cases alone.

**Comment by xiaofan-iit** [comment]
@rbtying Sorry that I didn't answer your primary question. In general, I agree with @chnlyi. For your example, 2233 does not require one to break a triplet such as 444x and one just need to play two pairs; however, when we play, 444 does not require one break a tractor and just need to play any pair plus a single. I personally think it makes sense, because 444x does not beat 2233 thus we need not require 444 break a tractor. What do you think?

**Comment by rbtying** [comment]
@chnlyi after #258 , the implementation should correctly require partial-decompositions (i.e. XXXYYY -> XXXYY), as well as matching (I think) the ordering you think is intuitive.
