### ISSUE TITLE
Support a post-ace no-trump rank

### ISSUE THREAD

**Issue by rbtying** [rbtying/shengji#243]
The no-trump rank should be implemented as the same as a normal rank, except that there is no bid process (since there's no trump) and jokers are trump.

required work:
- convert rank from a Number to a sum of Number and NT
- handle cases where there is no trump number
- require that a landlord is selected for the NT case
- change confetti to fire on defending no-trump rather than on A
- probably make this configurable

**Comment by czhang23** [comment]
I would like to work on this.  But, I don't want to spend time to setup a box to install all required components to build/run this project.  By any chance, you have a box I can SSH in to work on this?

**Comment by rbtying** [comment]
@czhang23 I was bored and built it just now. I don't have a free SSH box, unfortunately, but do you want to review the code?

**Comment by czhang23** [comment]
I read all changes.  I never used Rust before so my knowledge is very limited.  But I find all change elements I could think of.  Do you want to do a beta test before release?  My friend and I would be happy to test for you.

**Comment by rbtying** [comment]
@czhang23 It would be great if you and your group could beta test! It's running at https://robertying.com/shengji-beta. Let me know if anything breaks?

**Comment by czhang23** [comment]
I don't know if playing NT makes sense when "look for friends".  But if leader is "determined by bid", 
the player with Rank NT should be able to bid with any single LJ or HJ.
Other may continue to over-bid with a couple of rank cards.  Player with Rank NT may over-bid again with a couple of Joker.

Most cases, we play NT when leader is set.
In this case, nobody should have option to bid at all.  At the end of drawing, "reveal cards from bottom" should not be available.  And the leader should have option to "pick cards from bottom".

A minor improvement: Add player's ID to the beginning of the title of page so it is shown in browser's tab.

When a rank-NT player wins by 1 level, his next rank stays at NT.  Should it be 2?

When a rank-A player wins by 1 level, will his next rank be NT?

**Comment by rbtying** [comment]
Thanks for testing!

> I don't know if playing NT makes sense when "look for friends". But if leader is "determined by bid",
the player with Rank NT should be able to bid with any single LJ or HJ.

For now, I implemented it so the player with rank NT can never bid, so they only get to play if they are defending. Do you think this is worth handling specially, given that (by the time you get there) pretty much always the leader is set?

> Most cases, we play NT when leader is set.
> In this case, nobody should have option to bid at all. At the end of drawing, "reveal cards from bottom" should not be available. And the leader should have option to "pick cards from bottom".

I think this is implemented?

> A minor improvement: Add player's ID to the beginning of the title of page so it is shown in browser's tab.
This is a great idea!

> When a rank-NT player wins by 1 level, his next rank stays at NT. Should it be 2?
Hm, this is a bug. It should be 2, yes.

> When a rank-A player wins by 1 level, will his next rank be NT?
Yes, it should be!

**Comment by czhang23** [comment]
I don't know if playing NT makes sense when "look for friends". But if leader is "determined by bid",
the player with Rank NT should be able to bid with any single LJ or HJ.

For now, I implemented it so the player with rank NT can never bid, so they only get to play if they are defending. Do you think this is worth handling specially, given that (by the time you get there) pretty much always the leader is set?
----------- This needs to be implemented, at least for regular play (not finding friends version).  We have a rule that if a player who is the leader or the opposite of leader has less than 3 trump cards, or the player who is not with the leader has less than 20 score cards, the player has an option to reset the game and then we bid for leader.  This does happen sometimes.  In this case, we need to bid NT.  I understand this a big change because bidding with one LJ/HJ is a new thing for the system.
FYI, in our version, over-bid only changes the trump cards but doesn't change the leader.  Not important to have this option though.

Most cases, we play NT when leader is set.
In this case, nobody should have option to bid at all. At the end of drawing, "reveal cards from bottom" should not be available. And the leader should have option to "pick cards from bottom".

I think this is implemented?
----------- Now, "reveal cards from bottom" shows.  It should be disabled.

**Comment by rbtying** [comment]
@czhang23, thanks for the feedback.

I updated https://robertying.com/shengji-beta. If you have a chance, please take a look?

**Comment by czhang23** [comment]
The below FSM is for "first bidding for leader and subsequent bidding for trump".  You may load it into edotor.net to view.
For bidding for both leader/trump, it is very complicated.  My friend will draw it later to submit.
              The current implement has at least one flaw.  Bidding single HL or JL should not overbid a single rank card.

-----BEGIN--------------------------------
digraph finite_state_machine {
	// rankdir=LR;

	node [shape = doublecircle]; "Reset Game" "Start Game, Rank 2" "Start Game, Rank 2, NoTrump" "Start Game, Rank NT";
	node [shape = circle];

	"No Bid" -> "Reset Game" [ label = "No Card to Draw" ];
	"Rank NT" -> "Start Game, Rank NT" [ label = "No Card to Draw" ];
	"No Bid" -> "Rank 2" [ label = "Bid 2" ];
	"No Bid" -> "Rank NT" [ label = "Bid J" ];
	"No Bid" -> "Rank NT" [ label = "Bid couple of J" ];
    "Rank 2" -> "Rank 2, NoTrump" [ label = "Bid couple of J" ];
    "Rank 2" -> "Rank 2, Secured" [ label = "Bid couple of 2" ];
	"No Bid" -> "Rank 2, Secured" [ label = "Bid couple of 2" ];
    "Rank 2, Secured" -> "Rank 2, NoTrump" [ label = "Bid couple of J" ];
	"No Bid" -> "No Bid" [ label = "Draw" ];
	"Rank 2" -> "Rank 2" [ label = "Draw" ];
	"Rank NT" -> "Rank NT" [ label = "Draw" ];
    "Rank 2, Secured" -> "Rank 2, Secured" [ label = "Draw" ];
    "Rank 2, NoTrump" -> "Rank 2, NoTrump" [ label = "Draw" ];
	"Rank 2, NoTrump" -> "Start Game, Rank 2, NoTrump" [ label = "No Card to Draw" ];
	"Rank 2, Secured" -> "Start Game, Rank 2" [ label = "No Card to Draw" ];
	"Rank 2" -> "Start Game, Rank 2" [ label = "No Card to Draw" ];
}
----------END------------------------------------
