### ISSUE TITLE
Ordering after a 2x3 tractor

### ISSUE THREAD

**Issue by xiaofan-iit** [rbtying/shengji#257]
I would argue that, to be consistent, the players should play two triples first after a starting play of 2x3 tractor, followed by a triple, a pair and a single, followed by a 2x2 tractor and 2 singles, followed by 1 pairs and 2 singles, followed by all singles. For example, after a trick started with [555666], if a player has two triples, then two triples have to be played such as [AAA QQQ];  if the player has one triple and a a pair,  then e.g. [AAA QQ 3] is played; if the player has one triple and no other pairs, then e.g. [AAA 3 7 8] is played'; if the player has no triples but has a 2x2 tractor, then e.g. [AAKK 3 4] is played; if the player has no triples or 2x2 tractors, then two pairs is player e.g. [AA QQ 3 4]. 
Right now, one has to play a 2x2 tractor first after 2x3 tractor and the player does not have to play any triple if any. For example, after [555666](spade), a player has (AAA JJQQ 3 4) in spade, then one has to play [JJQQ 3 4]. I think it is not consistent with 2x3 tractors should be thought of triples first.

**Comment by rbtying** [comment]
In order to keep the decomposition easier to understand, I've chosen to (in cases of ambiguity like this) prioritize the base-decomposition-order (i.e. triple->pair->single) over the tractor-decomposition order (3-tractor->2-tractor). So, what's [implemented](https://github.com/rbtying/shengji/pull/258/files#diff-af5ae88afbd370007ea203c50ac5c43ff70ca22e4ad9d57ed2e8bd20b33e6d1fR661) is now a tractor of triples, followed by a pair of triples, followed by an adjacent triple and pair, followed, by a non-adjacent triple and pair, followed by a triple, followed by a 3-tractor of pairs (this is maybe controversial), followed by a tractor and a pair, followed by a three pairs, followed by a tractor and two random cards.

This does resolve the key issue, though, which is that a tractor of triples should draw triples.

**Comment by xiaofan-iit** [comment]
@rbtying Thanks. That's better, although "followed by a 3-tractor of pairs (this is maybe controversial), followed by a tractor and a pair, followed by a three pairs," maybe controversial.
