### ISSUE TITLE
option to remove joker pairs for large number of decks

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#290]
@rbtying Hope you can read Chinese. Or I can try to translate for you. 

This request comes from a friend of a friend of a friend... :) Also looks like they wanted to buy you coffee but could not...

打牌软件很受欢迎，我介绍到另一个群，每周末都有人打。这个群比较大，常常一上就是7-8家。这样底牌就有14-16张，王炸也太多。能不能跟你们朋友孩子说一下，这种情况可以选择6-8张底牌，通过放弃大小王来平衡。比如8家16人打，留8张底牌，放弃4大4小王，每人还是26张牌。我们也一直说要给这个孩子捐喝咖啡的钱，帮不帮都会捐，但是没有Venmo帐号，你们会怎么做？谢谢

**Comment by rbtying** [comment]
Hi Jack! My Chinese isn't the best, but if I understand correctly:

They want to support more players and have more decks, but that results in too many (or too few) cards on the bottom. So, to balance that, they want to pull jokers out of the deck so that the bottom can have fewer cards.

In #289 (to be deployed tomorrow), I added support for choosing a smaller number of cards on the bottom, but it will pull out small cards (i.e. 2s or 3s) rather than pulling out jokers. Does that solve the problem for your friend^3? If not, I think the main tricky bit is just figuring out how to make a UI that can configure removing some of the jokers from the game.

(as for the Venmo issue... I suppose I should set up a Stripe integration because I work there haha. And that should support more payment methods than Venmo)

**Comment by cai-jack** [comment]
You read it perfectly! Looks like they are mostly concerned about too many joker pairs. Is it possible to add an option to remove jokers instead of small cards in #289 ?
