### ISSUE TITLE
Chat window shows limited card playing history

### ISSUE THREAD

**Issue by fly-high-bj** [rbtying/shengji#303]
Hi Robert, great program and it brings a lot of fun among our friends. 
A quick minor note, it seems that when we have a 'roomful' of people and many decks, the chat window would only show the last messages, probably up to 100, including the hands played and broadcasting messages. 
I looked at the code and it seems that the setting is outside this repo, probably on your server?

Anyway, this is a minor issue. It would be interesting to show the full card playing history for a game. 

Thanks very much.

**Comment by rbtying** [comment]
Hi, thanks for reporting! Today the messages are stored only on the client side, which is why they're not in an obvious place. See here: https://github.com/rbtying/shengji/blob/master/frontend/src/websocketHandler.ts#L12

It might make sense to start storing messages on the server, though -- for this and other reasons!

**Comment by fly-high-bj** [comment]
Thanks for the quick response! Could we then at least increase the number? Even that there is still chances of records being truncated, but maybe 300 would be sufficient for most cases.

**Comment by rbtying** [comment]
I'd accept a PR :)

**Comment by fly-high-bj** [comment]
PR submitted. ;)
