### ISSUE TITLE
Re-trumping a trumped single-single-pair throw with two pairs matches the 2nd pair incorrectly.

### ISSUE THREAD

**Issue by NZadeh** [rbtying/shengji#397]
This is an excerpt of the game log, with trump 2♣, where P2 incorrectly wins the trick, despite the fact that P5's play should beat P2's play. (66♣ > 55♣, 2♣ > A♣, 2♣ > 2♠)

```
GAME: P1 played 8♦8♦J♦Q♦
GAME: P2 played 5♣5♣A♣2♠   # (trumps the throw, currently winning)
GAME: P3 played Q♠J♣J♣K♣
GAME: P4 played 3♠3♠7♣8♣
GAME: P5 played 6♣6♣2♣2♣   # (should beat P2 but doesn't)
GAME: P2 wins the trick and gets 20 points   # (incorrect, P5 should win)
```

My best guess is that the logic is using "any pair" (or the highest) to "beat" the first pair, and incorrectly using the singles from the lower pair to match against P2's high singles.

The fix might be: use the lowest possible winning pair (or triple, tractor, {biggest component of the throw}, etc), then determine whether the smaller components of the throw can be beaten in the same way recursively (using the lowest possible of each shape that needs trumping).

**Comment by rbtying** [comment]
ooh, thanks for the bug report! will try to repro and then fix

I think your guess is probably right, but we'll check.

**Comment by rbtying** [comment]
So, it turns out what's actually happening here is:

The mapping of a given set of cards, (e.g. 6♣6♣2♣2♣) to a given trick-format (e.g. 2/1/1) is treated as fixed (`attempt_format_match` returns only one possible mapping, even though there may be more than one), as we can see [here](https://github.com/rbtying/shengji/blob/master/core/src/ordered_card.rs#L107)

It so happens that, in your example, the one it chose is the weaker mapping! but the point in the code where it does this logic isn't quite the place where it evaluates which trick wins...
